# ── Server ──────────────────────────────────────
quarkus.http.port=8080

# ── DynamoDB ────────────────────────────────────
quarkus.dynamodb.aws.region=us-east-1
quarkus.dynamodb.aws.credentials.type=default

# ── CORS ────────────────────────────────────────
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000,http://spiceroadtruck-frontend.s3-website-us-east-1.amazonaws.com,https://spiceroadtruck.com
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Accept,Authorization

quarkus.package.jar.type=legacy-jar